# Generated by Django 5.0.2 on 2024-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_grievance_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(default=0, max_length=10),
        ),
    ]
